LaundryOnline/Models/Coupon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LaundryOnline.Models
{
    public class Coupon
    {
        [Key]
        [DisplayName("Coupon Id")]
        public string CouponId { get; set; }

        [DisplayName("Coupon Name")]
        [Required]
        [StringLength(150)]
        public string CouponName { get; set; }

        [DisplayName("Discount")]
        [Range(1, Int32.MaxValue)]
        [Required]
        public double Discount { get; set; }

        [DisplayName("Status")]
        [DefaultValue(1)]
        public byte Status { get; set; }

        [DisplayName("Created At")]
        public DateTime CreatedAt { get; set; }

        [DisplayName("Expiration At")]
        [Required]
        public DateTime ExpirationDate { get; set; }

        public ICollection<UsedCoupon> UsedCoupons { get; set; }

        public ICollection<Order> Orders { get; set; }
    }
}

LaundryOnline/Areas/Admin/Controllers/CouponsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaundryOnline.Models;
using X.PagedList;
using NToastNotify;
using Microsoft.AspNetCore.Authorization;

namespace LaundryOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CouponsController : Controller
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;
        public CouponsController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }

        // GET: Admin/Coupons
        public async Task<IActionResult> Index(int? page, string name)
        {
            page = page ?? 1;
            int pageSize = 6;
            var coupons = _context.Coupons.AsQueryable();
            if (!string.IsNullOrEmpty(name))
            {
                coupons = coupons.Where(j => j.CouponName.Contains(name));
            }

            foreach (var item in coupons)
            {
                if (item.ExpirationDate < DateTime.UtcNow.Date)
                {
                    item.Status = 0;
                    _context.Entry(item).State = EntityState.Modified;
                }
                else
                {
                    item.Status = 1;
                    _context.Entry(item).State = EntityState.Modified;
                }
            }
            await _context.SaveChangesAsync();

            return View(await coupons.ToPagedListAsync(page, pageSize));
        }

        // GET: Admin/Coupons/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupons
                .FirstOrDefaultAsync(m => m.CouponId == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // GET: Admin/Coupons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Coupons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CouponId,CouponName,Discount,Status,CreatedAt,ExpirationDate")] Coupon coupon)
        {
            coupon.Status = 1;
            coupon.CreatedAt = DateTime.UtcNow.Date;
            if (ModelState.IsValid)
            {
                _context.Add(coupon);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Create new service successfully");
                return RedirectToAction(nameof(Index));
            }
            _toastNotification.AddErrorToastMessage("Create new service failed");
            return View(coupon);
        }

        // GET: Admin/Coupons/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupons.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        // POST: Admin/Coupons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CouponId,CouponName,Discount,Status,CreatedAt,ExpirationDate")] Coupon coupon)
        {
            if (id != coupon.CouponId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coupon);
                    await _context.SaveChangesAsync();
                    _toastNotification.AddSuccessToastMessage("Update successfully");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CouponExists(coupon.CouponId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        _toastNotification.AddErrorToastMessage("Update failed");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }

        // GET: Admin/Coupons/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupons
                .FirstOrDefaultAsync(m => m.CouponId == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // POST: Admin/Coupons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var coupon = await _context.Coupons.FindAsync(id);

            try
            {
                _context.Coupons.Remove(coupon);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Delete service " + coupon.CouponName + " successfully");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Delete service " + coupon.CouponName + " failed");
            }
            return RedirectToAction(nameof(Index));
        }

        private bool CouponExists(string id)
        {
            return _context.Coupons.Any(e => e.CouponId == id);
        }
    }
}

LaundryOnline/Areas/Admin/Views/Coupons/Create.cshtml
@model LaundryOnline.Models.Coupon

@{
    ViewData["Title"] = "Create";
}
<div class="page-header row">
    <div class="header-sub-title col-md-12">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item">
                <i class="anticon anticon-home m-r-5"></i>Home
            </a>
            <a class="breadcrumb-item" asp-controller="Coupons" asp-action="Index">Coupons</a>
            <span class="breadcrumb-item active">Add Coupon</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4>
            Add New Coupon
        </h4>
        <div class="m-t-25">
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="CouponName" class="control-label"></label>
                            <input asp-for="CouponName" class="form-control" />
                            <span asp-validation-for="CouponName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Discount" class="control-label"></label>
                            <input asp-for="Discount" class="form-control" />
                            <span asp-validation-for="Discount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ExpirationDate" class="control-label"></label>
                            <input asp-for="ExpirationDate" type="date" class="form-control" />
                            <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-success" />
                            <a asp-action="Index" class="btn btn-primary">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaundryOnline/Areas/Admin/Views/Coupons/Edit.cshtml
@model LaundryOnline.Models.Coupon

@{
    ViewData["Title"] = "Edit";
}
<div class="page-header row">
    <div class="header-sub-title col-md-12">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item">
                <i class="anticon anticon-home m-r-5"></i>Home
            </a>
            <a class="breadcrumb-item" asp-controller="Coupons" asp-action="Index">Coupons</a>
            <span class="breadcrumb-item active">Edit Coupon</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4>
            Edit Coupon
        </h4>
        <div class="m-t-25">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="CouponId" />
                        <div class="form-group">
                            <label asp-for="CouponName" class="control-label"></label>
                            <input asp-for="CouponName" class="form-control" />
                            <span asp-validation-for="CouponName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Discount" class="control-label"></label>
                            <input asp-for="Discount" class="form-control" />
                            <span asp-validation-for="Discount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ExpirationDate" class="control-label"></label>
                            <input asp-for="ExpirationDate" type="date" class="form-control" />
                            <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                        </div>
                        <fieldset class="form-group">
                            <div class="row">
                                <label class="col-form-label col-sm-3 pt-0">Status</label>
                                <div class="col-sm-9">
                                    <div class="radio">
                                        <input asp-for="Status" type="radio" value="1" id="radio1">
                                        <label for="radio1">Active</label>
                                    </div>
                                    <div class="radio">
                                        <input asp-for="Status" type="radio" value="0" id="radio2">
                                        <label for="radio2">Non Active</label>
                                    </div>

                                </div>
                            </div>
                        </fieldset>
                        <input type="hidden" asp-for="CreatedAt" class="form-control" />
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-success" />
                            <a asp-action="Index" class="btn btn-primary">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaundryOnline/Areas/Admin/Views/Coupons/Index.cshtml
@model X.PagedList.IPagedList<LaundryOnline.Models.Coupon>
@using X.PagedList.Mvc.Core;
@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
<div class="page-header row">
    <div class="header-sub-title col-md-12">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item">
                <i class="anticon anticon-home m-r-5"></i>Home
            </a>
            <a class="breadcrumb-item" asp-controller="Coupons" asp-action="Index">Coupons</a>
            <span class="breadcrumb-item active">List Coupons</span>
        </nav>
    </div>
    <div class="col-md-12" style="display: flex;">
        <form action="" method="get" class="form-inline ml-lg-auto">
            <div class="form-group">
                <label class="sr-only" for="">label</label>
                <input class="form-control" name="name" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-icon btn-default mr-1"><i class="fas fa-search"></i></button>
        </form>
        <a asp-action="Create">
            <i class="anticon anticon-plus btn btn-icon btn-success"></i>
        </a>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Coupon Id
                    </th>
                    <th>
                        Coupon Name
                    </th>
                    <th>
                        Discount
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Created At
                    </th>
                    <th>
                        Expiration Date
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CouponId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CouponName)
                        </td>
                        <td>
                            @string.Format("{0:C0}", item.Discount)
                        </td>
                        <td>
                            @if (item.Status == 0)
                            {
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-danger badge-dot m-r-10"></div>
                                    <div>Non Active</div>
                                </div>
                            }
                            else
                            {
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <div>Active</div>
                                </div>
                            }

                        </td>
                        <td>
                            @item.CreatedAt.ToShortDateString()
                        </td>
                        <td>@item.ExpirationDate.ToShortDateString()</td>
                        <td class="d-flex">
                            <a asp-action="Edit" asp-area="Admin" asp-route-id="@item.CouponId">
                                <i class="anticon anticon-form btn btn-icon btn-warning mr-2"></i>
                            </a>
                            <a asp-action="Details" asp-area="Admin" asp-route-id="@item.CouponId">
                                <i class="anticon anticon-info-circle btn btn-icon btn-primary mr-2"></i>
                            </a>
                            <form asp-action="Delete" asp-route-id="@item.CouponId" method="post">
                                <button type="submit" class="btn btn-icon btn-danger" onclick="return functionConfirm(this)">
                                    <i class="anticon anticon-delete btn btn-icon btn-danger"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <div class="row">
            <div class="col-sm-12 col-md-5">
                <div class="dataTables_info">
                    Showing
                    <span class="text-danger">
                        @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                    </span>
                    of
                    <b>
                        @Model.PageCount
                    </b>
                    pages
                </div>
            </div>
            <div class="col-sm-12 col-md-7">
                <div class="float-right ">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                        new PagedListRenderOptions
                        {
                            LiElementClasses = new string[] { "page-item" },
                            PageClasses = new string[] { "page-link" }
                        }
                    )
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript">
        function functionConfirm(event) {
            swal({
                title: 'Are you sure?',
                text: "You will not be able to recover this item",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Yes',
                confirmButtonClass: 'btn btn-success'
            }, function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    return true;
                } else {
                    return false;
                }
            });
            return false;
        }
    </script>
}