LaundryOnline/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LaundryOnline.Models
{
    public class User
    {
        [Key]
        [DisplayName("User Id")]
        public string UserId { get; set; }

        [DisplayName("Full Name")]
        [Required]
        [StringLength(80)]
        public string FullName { get; set; }

        [DisplayName("Email")]
        [Required]
        [EmailAddress]
        public string EmailAddress { get; set; }

        [DisplayName("Phone Number")]
        [Required]
        [Phone]
        public string ContactNumber { get; set; }

        [DisplayName("Address")]
        [Required]
        [StringLength(150)]
        public string Address { get; set; }

        [DisplayName("UserName")]
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }

        [DisplayName("Password")]
        [Required]
        [MinLength(6)]
        public string Password { get; set; }

        [DisplayName("Status")]
        [DefaultValue(1)]
        public byte Status { get; set; }

        [DisplayName("Role")]
        [DefaultValue(1)]
        public byte Role { get; set; }

        public ICollection<Blog> Blogs { get; set; }

        public ICollection<UsedCoupon> UsedCoupons { get; set; }

        public ICollection<Order> Orders { get; set; }
    }
}

LaundryOnline/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BarcodeLib;
using LaundryOnline.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using Rotativa.AspNetCore;
using X.PagedList;

namespace LaundryOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;

        public UserController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }

        public async Task<IActionResult> Index(int? page, string name)
        {
            page = page ?? 1;
            int pageSize = 3;
            var users = _context.Users.Where(x => x.Role == 1).AsQueryable();
            if (!string.IsNullOrEmpty(name))
            {
                users = users.Where(j => j.UserName.Contains(name) || j.FullName.Contains(name) || j.EmailAddress.Contains(name));
            }
            return View(await users.ToPagedListAsync(page, pageSize));
        }
  
        public async Task<IActionResult> Edit(string id)
        {
            var user = _context.Users.Find(id);
            if (user != null)
            {
                if (user.Status == 1)
                {
                    user.Status = 0;
                    _context.Entry(user).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                else
                {
                    user.Status = 1;
                    _context.Entry(user).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));      
            }
            else
            {
                return NotFound();
            }
 
        }
        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
        public IActionResult Details()
        {
            User user = _context.Users.Where(u=>u.UserId== HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value).FirstOrDefault();
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        public IActionResult ViewAsPDF()
        {
            List<User> users = _context.Users.ToList(); 
            return new ViewAsPdf(users, ViewData);
        }
        private static Byte[] ConvertImageToByte(Image img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
}

LaundryOnline/Areas/Admin/Views/User/Details.cshtml
@model LaundryOnline.Models.User

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>
<div class="page-header row">
    <div class="header-sub-title col-md-12">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item">
                <i class="anticon anticon-home m-r-5"></i>Home
            </a>
            <a class="breadcrumb-item" asp-controller="User" asp-action="Details">User</a>
            <span class="breadcrumb-item active">Detail User</span>
        </nav>
    </div>
    <div class="col-md-12" style="display: flex;">

    </div>
</div>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-md-7">
                    <div class="d-md-flex align-items-center">

                        <div class="text-center text-sm-left m-v-15 p-l-30">
                            <h2 class="m-b-5">@Model.FullName</h2>
                            <p class="text-opacity font-size-13">@Model.UserId</p>
                            <p class="text-dark m-b-20">@Model.Address</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="d-md-block d-none border-left col-1"></div>
                        <div class="col">
                            <ul class="list-unstyled m-t-10">
                                <li class="row">
                                    <p class="col-sm-4 col-4 font-weight-semibold text-dark m-b-5">
                                        <i class="m-r-10 text-primary anticon anticon-mail"></i>
                                        <span>Email: </span>
                                    </p>
                                    <p class="col font-weight-semibold"> @Model.EmailAddress</p>
                                </li>
                                <li class="row">
                                    <p class="col-sm-4 col-4 font-weight-semibold text-dark m-b-5">
                                        <i class="m-r-10 text-primary anticon anticon-phone"></i>
                                        <span>Phone: </span>
                                    </p>
                                    <p class="col font-weight-semibold"> @Model.ContactNumber</p>
                                </li>
                                <li class="row">
                                    <p class="col-sm-4 col-5 font-weight-semibold text-dark m-b-5">
                                        <i class="m-r-10 text-primary anticon anticon-compass"></i>
                                        <span>User Name: </span>
                                    </p>
                                    <p class="col font-weight-semibold"> @Model.UserName</p>
                                </li>
                            </ul>
                            <div class="d-flex font-size-22 m-t-15">
                                <a href="" class="text-gray p-r-20">
                                    <i class="anticon anticon-facebook"></i>
                                </a>
                                <a href="" class="text-gray p-r-20">
                                    <i class="anticon anticon-twitter"></i>
                                </a>
                                <a href="" class="text-gray p-r-20">
                                    <i class="anticon anticon-behance"></i>
                                </a>
                                <a href="" class="text-gray p-r-20">
                                    <i class="anticon anticon-dribbble"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

LaundryOnline/Areas/Admin/Views/User/Index.cshtml
@model X.PagedList.IPagedList<LaundryOnline.Models.User>
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
<div class="page-header row">
    <div class="header-sub-title col-md-12">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item">
                <i class="anticon anticon-home m-r-5"></i>Home
            </a>
            <a class="breadcrumb-item" asp-controller="User" asp-action="Index">User</a>
            <span class="breadcrumb-item active">List User</span>
        </nav>
    </div>
    <div class="col-md-12" style="display: flex;">
        <form action="" method="get" class="form-inline ml-lg-auto">
            <div class="form-group">
                <label class="sr-only" for="">label</label>
                <input class="form-control" name="name" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-icon btn-default mr-1"><i class="fas fa-search"></i></button>
            <a asp-action="ViewAsPDF" asp-area="Admin">
                <i class="fas fa-print btn btn-icon btn-success mr-2"></i>
            </a>
        </form>
        
    </div>
</div>


<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Full Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>
                        Address
                    </th>
                    <th>
                        UserName
                    </th>
                    <th>
                        Status
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="text-capitalize">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EmailAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactNumber)
                    </td>
                    <td class="text-capitalize">
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>

                    @if (@item.Status == 0)
                    {
                        <td>
                            <div class="d-flex align-items-center">
                                <div class="badge badge-danger badge-dot m-r-10"></div>
                                <div>Non Active</div>
                            </div>
                        </td>
                        <td class="d-flex">
                            <a asp-action="Edit" asp-area="Admin" asp-route-id="@item.UserId">
                                <i class="anticon anticon-lock btn btn-icon btn-danger mr-2"></i>
                            </a>

                        </td>
                    }
                    else
                    {
                        <td>
                            <div class="d-flex align-items-center">
                                <div class="badge badge-success badge-dot m-r-10"></div>
                                <div>Active</div>
                            </div>
                        </td>
                        <td class="d-flex">
                            <a asp-action="Edit" asp-area="Admin" asp-route-id="@item.UserId">
                                <i class="anticon anticon-unlock btn btn-icon btn-success mr-2"></i>
                            </a>
                        </td>
                    }
                    


                </tr>
                }
            </tbody>
        </table>
        <hr />
        <div class="row">
            <div class="col-sm-12 col-md-5">
                <div class="dataTables_info">
                    Showing
                    <span class="text-danger">
                        @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                    </span>
                    of
                    <b>
                        @Model.PageCount
                    </b>
                    pages
                </div>
            </div>
            <div class="col-sm-12 col-md-7">
                <div class="float-right ">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                        new PagedListRenderOptions
                        {
                            LiElementClasses = new string[] { "page-item" },
                            PageClasses = new string[] { "page-link" }
                        }
                    )
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript">
        function functionConfirm(event) {
            swal({
                title: 'Are you sure?',
                text: "You will not be able to recover this item",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Yes',
                confirmButtonClass: 'btn btn-success'
            }, function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    return true;
                } else {
                    return false;
                }
            });
            return false;
        }
    </script>
}

LaundryOnline/Areas/Admin/Views/User/ViewAsPDF.cshtml
@model IEnumerable<LaundryOnline.Models.User>
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Laralink">
    <!-- Site Title -->
    <link rel="stylesheet" href="~/pdf/style.css">
</head>

<body>
    <div class="tm_container">
        <div class="tm_invoice_wrap">
            <div class="tm_invoice tm_style1 tm_type3" id="tm_download_section">
                <div class="tm_shape_1">
                    <svg width="1100" height="151" viewBox="0 0 1100 151" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1100 0.889398H0V150.889H184.505C216.239 150.889 246.673 141.531 269.113 124.872L359.112 58.0565C381.553 41.3977 411.987 32.0391 443.721 32.0391H850V0.889398Z" fill="#007AFF" fill-opacity="0.1" />
                    </svg>
                </div>
                <div class="tm_shape_2">
                    <svg width="1100" height="151" viewBox="0 0 1100 151" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 150.889H850V0.889408H665.496C633.762 0.889408 603.327 10.2481 580.887 26.9081L490.888 93.7224C468.447 110.381 438.014 119.74 406.279 119.74H0V150.889Z" fill="#007AFF" fill-opacity="0.1" />
                    </svg>
                </div>
                <div class="tm_invoice_in">
                    <div class="tm_invoice_head tm_align_center tm_mb20">

                        <div class="tm_invoice_left">
                            <div class="tm_logo"><img src="https://dtdrycleaning.wpengine.com/wp-content/themes/dry-cleaning/images/logo.png" alt="Logo" width="250"></div>
                        </div>
                    </div>
                    <div class="tm_invoice_info_list">
                        <br />
                        @*<p class="tm_invoice_date tm_m0">Date: <b class="tm_primary_color"> @Model.CreatedAt.Value.ToLongDateString() </b></p>*@
                    </div>
                    <
                    <div class="tm_table tm_style1 tm_mb30">
                        <div class="tm_table_responsive">
                            <table class="tm_border_bottom">
                                <thead>
                                    <tr class="tm_border_top">
                                        <th class="tm_width_1 tm_semi_bold tm_primary_color tm_accent_bg_10">Full Name</th>
                                        <th class="tm_width_1 tm_semi_bold tm_primary_color tm_accent_bg_10 tm_text_right">Email</th>
                                        <th class="tm_width_2 tm_semi_bold tm_primary_color tm_accent_bg_10 tm_text_right">Phone</th>
                                        <th class="tm_width_2 tm_semi_bold tm_primary_color tm_accent_bg_10 tm_text_right">Address</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model )
                                    {
                                    <tr>
                                        <td class="tm_width_2 tm_text_right">@item.FullName</td>
                                        <td class="tm_width_1 tm_text_right">@item.EmailAddress</td>
                                        <td class="tm_width_2 tm_text_right">@item.ContactNumber</td>
                                        <td class="tm_width_2 tm_text_right">@item.Address</td> 
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    <div class="tm_padd_15_20">
                        <p class="tm_mb2"><b class="tm_primary_color">Terms & Conditions:</b></p>
                        <ul class="tm_m0 tm_note_list">
                            <li>All claims relating to quantity or shipping errors.</li>
                            <li>Delivery dates are not guaranteed and Seller.</li>
                        </ul>
                    </div><!-- .tm_note -->
                </div>
            </div>
        </div>
    </div>
</body>
</html>