LaundryOnline/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LaundryOnline.Models
{
    public class Order
    {
        [Key]
        [DisplayName("Order Id")]
        public string OrderId { get; set; }

        [DisplayName("Full Name")]
        [Required]
        [StringLength(80)]
        public string FullName { get; set; }

        [DisplayName("Email")]
        [Required]
        [EmailAddress]
        public string EmailAddress { get; set; }

        [DisplayName("Phone Number")]
        [Required]
        [Phone]
        public string ContactNumber { get; set; }

        [DisplayName("Address")]
        [Required]
        [StringLength(150)]
        public string Address { get; set; }

        [DisplayName("Total Price")]
        [Required]
        [Range(1, Int32.MaxValue)]
        public double Price { get; set; }

        [DisplayName("Note")]
        public string Note { get; set; }

        [DisplayName("Payment Status")]
        [DefaultValue(1)]
        public byte PaymentStatus { get; set; }

        [DisplayName("Order Status")]
        [DefaultValue(1)]
        public byte OrderStatus { get; set; }

        [DisplayName("Created At")]
        public DateTime? CreatedAt { get; set; }

        [DisplayName("Updated At")]
        public DateTime? UpdatedAt { get; set; }

        [DisplayName("User")]
        [ForeignKey("User")]
        public string UserId { get; set; }

        [DisplayName("Payment")]
        [ForeignKey("Payment")]
        [Required]
        public string PaymentId { get; set; }

        [DisplayName("Coupon")]
        [ForeignKey("Coupon")]
        public string CouponId { get; set; }

        [DisplayName("User")]
        public User User { get; set; }

        [DisplayName("Payment")]
        public Payment Payment { get; set; }

        [DisplayName("Coupon")]
        public Coupon Coupon { get; set; }

        public ICollection<OrderItem>  OrderItems { get; set; }
    }
}

LaundryOnline/Areas/Admin/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaundryOnline.Models;
using X.PagedList;
using QRCoder;
using System.Drawing;
using System.IO;
using NToastNotify;
using BarcodeLib;
using Rotativa.AspNetCore;

namespace LaundryOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrdersController : Controller
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;
        public OrdersController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }

        // GET: Admin/Orders
        public async Task<IActionResult> Index(int? page,string name,string email,string address)
        {
            page = page ?? 1;
            int pageSize = 6;
            var laundryOnlineContext = _context.Orders.Include(o => o.Coupon).Include(o => o.Payment).Include(o => o.User).AsQueryable();
            ViewBag.LaundryStatus = laundryOnlineContext;
            if (!string.IsNullOrEmpty(name))
            {
                laundryOnlineContext = laundryOnlineContext.Where(x => x.FullName.Contains(name) ||  x.Address.Contains(address) || x.EmailAddress.Contains(email));
            }
            foreach (var item in _context.Orders)
            {
                if (item.OrderStatus == 2)
                {
                    item.PaymentStatus = 1;
                    _context.Entry(item).State = EntityState.Modified;
                }
                else
                {
                    item.PaymentStatus = 0;
                    _context.Entry(item).State = EntityState.Modified;
                }
            }
            return View(await laundryOnlineContext.ToPagedListAsync(page, pageSize));
        }

        // GET: Admin/Orders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Coupon)
                .Include(o => o.Payment)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            ViewBag.OrderDetail = _context.OrderItems.Include(o => o.Unit).Where(o => o.OrderId == id).ToList();

            if (order == null)
            {
                return NotFound();
            }
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(order.OrderId, QRCodeGenerator.ECCLevel.Q);
            QRCoder.QRCode qrCode = new QRCoder.QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);
            ViewBag.QrCode = BitmapToBytes(qrCodeImage);

            Barcode barcode = new Barcode();
            Image img = barcode.Encode(TYPE.CODE128, order.OrderId, Color.Black, Color.White, 650, 80);
            ViewBag.Barcode = ConvertImageToByte(img);
            return View(order);
        }

        // GET: Admin/Orders/Create
        public IActionResult Create()
        {
            ViewData["CouponId"] = new SelectList(_context.Coupons, "CouponId", "CouponId");
            ViewData["PaymentId"] = new SelectList(_context.Payments, "PaymentId", "PaymentId");
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: Admin/Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,FullName,EmailAddress,ContactNumber,Address,Price,Note,PaymentStatus,OrderStatus,CreatedAt,UpdatedAt,UserId,PaymentId,CouponId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CouponId"] = new SelectList(_context.Coupons, "CouponId", "CouponId", order.CouponId);
            ViewData["PaymentId"] = new SelectList(_context.Payments, "PaymentId", "PaymentId", order.PaymentId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        public async Task<IActionResult> Edit(string id)
        {
            var order = _context.Orders.Find(id);
            if(order != null)
            {
                if (order.OrderStatus == 0)
                {
                    order.OrderStatus = 1;
                    _context.Entry(order).State = EntityState.Modified;
                    _toastNotification.AddSuccessToastMessage("Change order status successfully");
                    await _context.SaveChangesAsync();
                }
                else if(order.OrderStatus == 1)
                {
                    order.OrderStatus = 2;
                    _context.Entry(order).State = EntityState.Modified;
                    _toastNotification.AddSuccessToastMessage("Change order status  successfully");
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Change order status  failed");
                return NotFound();
            }
        }

        //public async Task<IActionResult> ChangePayment(string id)
        //{
        //    var order = _context.Orders.Find(id);
        //    if (order != null)
        //    {
        //        if (order.PaymentStatus == 0)
        //        {
        //            order.PaymentStatus = 1;
        //            _context.Entry(order).State = EntityState.Modified;
        //            _toastNotification.AddSuccessToastMessage("Change payment status successfully");
        //            await _context.SaveChangesAsync();
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    else
        //    {
        //        _toastNotification.AddErrorToastMessage("Change payment status  failed");
        //        return NotFound();
        //    }
        //}


        private bool OrderExists(string id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
        private static Byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
        public IActionResult ViewAsPDF(string id)
        {
            var order = _context.Orders
              .Include(o => o.Coupon)
              .Include(o => o.Payment)
              .Include(o => o.User)
              .FirstOrDefault(m => m.OrderId == id);
            ViewData["OrderDetail"] = _context.OrderItems.Include(o => o.Unit).Where(o => o.OrderId == order.OrderId).ToList();
            Barcode barcode = new Barcode();
            Image img = barcode.Encode(TYPE.CODE128, order.OrderId, Color.Black, Color.White, 650, 80);
            ViewData["Barcode"] = ConvertImageToByte(img);
            return new ViewAsPdf(order, ViewData);
        }
        private static Byte[] ConvertImageToByte(Image img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
        public IActionResult ViewAsPDFList()
        {
            List<Order> order = _context.Orders.ToList();
            
            return new ViewAsPdf(order);
        }
    }
}

LaundryOnline/Views/Orders/CheckBill.cshtml
@{
    ViewData["Title"] = "CheckBill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>
    <div class="tp-page-title-area pt-180 pb-185 position-relative fix" data-background="/assets/img/slider/breadcrumb-bg-1.jpg">
        <div class="tp-custom-container">
            <div class="row">
                <div class="col-12">
                    <div class="tp-page-title z-index">
                        <h2 class="breadcrumb-title">Your <span>Order</span></h2>
                        <div class="breadcrumb-menu">
                            <nav class="breadcrumb-trail breadcrumbs">
                                <ul class="trail-items">
                                    <li class="trail-item trail-begin">
                                        <a asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="trail-item trail-end"><span>Order</span></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="tp-pricing-area pt-120 pb-90">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="section-title-wrapper text-center mb-55 wow fadeInUp" data-wow-delay=".2s">
                        <h5 class="tp-section-subtitle common-yellow-shape mb-20 heading-color-black">Our Affordable Package</h5>
                        <h2 class="tp-section-title heading-color-black">Check Bill</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="tp-contact-form card">
                        <form asp-action="Details" asp-controller="Orders" method="get">
                            <div class="row custom-mar-20 card-body" style="padding: 50px;">
                                <div class="col-md-12 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20">
                                        <input placeholder="Enter your waybill code" name="id"/>
                                    </div>
                                </div>
                                <div class="col-md-12 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20">
                                        <p class="text-muted " style="padding-left: 40px;">
                                            Enter your bill of lading code to look up
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-12 custom-pad-20">
                                    <div class="tp-contact-form-field">
                                        <button type="submit" class="theme-btn text-capitalize" style="width: -webkit-fill-available;">
                                            Check bill of lading
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

LaundryOnline/Views/Orders/Create.cshtml
@model LaundryOnline.Models.Order
﻿@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var @total = 0;
}

<main class="">
    <div class="tp-page-title-area pt-180 pb-185 position-relative fix" data-background="/assets/img/slider/breadcrumb-bg-1.jpg">
        <div class="tp-custom-container">
            <div class="row">
                <div class="col-12">
                    <div class="tp-page-title z-index">
                        <h2 class="breadcrumb-title">Your <span>Order</span></h2>
                        <div class="breadcrumb-menu">
                            <nav class="breadcrumb-trail breadcrumbs">
                                <ul class="trail-items">
                                    <li class="trail-item trail-begin">
                                        <a asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="trail-item trail-end"><span>Order</span></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="tp-service-area-three pt-120 pb-90">
        <div class="container">
            <form asp-action="Create" class="custom-mar-20">
                <div class="row">
                    <div class="col-md-8 mb-4">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row custom-mar-20 ">
                            @if (ViewBag.Users != null)
                            {
                                <input asp-for="UserId" class="form-control custom-pad-20" value="@ViewBag.Users.UserId" type="hidden" />

                                <div class="col-md-6 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20 ">
                                        <label asp-for="FullName" class="control-label"></label>
                                        <input asp-for="FullName" class="form-control custom-pad-20" value="@ViewBag.Users.FullName" />
                                        <span asp-validation-for="FullName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20">
                                        <label asp-for="ContactNumber" class="control-label"></label>
                                        <input asp-for="ContactNumber" class="form-control" value="@ViewBag.Users.ContactNumber" />
                                        <span asp-validation-for="ContactNumber" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="tp-contact-form-field mb-20 custom-pad-20">
                                    <label asp-for="EmailAddress" class="control-label"></label>
                                    <input asp-for="EmailAddress" class="form-control" value="@ViewBag.Users.EmailAddress" />
                                    <span asp-validation-for="EmailAddress" class="text-danger"></span>
                                </div>
                                <div class="tp-contact-form-field mb-20 custom-pad-20">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" value="@ViewBag.Users.Address" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20 ">
                                        <label asp-for="FullName" class="control-label"></label>
                                        <input asp-for="FullName" class="form-control custom-pad-20" />
                                        <span asp-validation-for="FullName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 custom-pad-20">
                                    <div class="tp-contact-form-field mb-20">
                                        <label asp-for="ContactNumber" class="control-label"></label>
                                        <input asp-for="ContactNumber" class="form-control" />
                                        <span asp-validation-for="ContactNumber" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="tp-contact-form-field mb-20 custom-pad-20">
                                    <label asp-for="EmailAddress" class="control-label"></label>
                                    <input asp-for="EmailAddress" class="form-control" />
                                    <span asp-validation-for="EmailAddress" class="text-danger"></span>
                                </div>
                                <div class="tp-contact-form-field mb-20 custom-pad-20">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                            }
                            @if (HttpContextAccessor.HttpContext.Session.GetString("Coupon") != null)
                            {
                                <input asp-for="CouponId" value="@ViewBag.Coupon.CouponId" type="hidden" />
                            }
                            <div class="tp-contact-form-field mb-20 custom-pad-20">
                                <label asp-for="Note" class="control-label"></label>
                                <textarea asp-for="Note" class="form-control"></textarea>
                                <span asp-validation-for="Note" class="text-danger"></span>
                            </div>

                            <h5>I'll pay with&hellip;</h5>
                            <div class="list-group mb-20 custom-pad-20">
                                @foreach (var item in ViewBag.Payment)
                                {
                                    <div class="list-group-item border-0">
                                        <div class="list-group-item-heading">
                                            <div class="mb-20 custom-pad-20">
                                                <label class="font-weight-bold text-capitalize">
                                                    <input type="radio" asp-for="PaymentId" value="@item.PaymentId" checked>
                                                    @item.PaymentName
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                            <div class="col-md-12 custom-pad-20">
                                <div class="tp-contact-form-field">
                                    <button type="submit" class="theme-btn"><i class="flaticon-enter"></i> Checkout</button>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-4 mb-4">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-muted">Your cart</span>
                        </h4>
                        <ul class="list-group mb-3 z-depth-1">
                            @foreach (var item in ViewBag.Carts)
                            {
                                <li class="list-group-item d-flex justify-content-between lh-condensed">
                                    <div>
                                        <h6 class="my-0">@item.UnitName</h6>
                                    </div>
                                    <span class="text-muted">@string.Format("{0:C}", item.UnitPrice)</span>
                                </li>
                                total += item.UnitPrice * item.Quantity;

                            }
                            @if (HttpContextAccessor.HttpContext.Session.GetString("Coupon") != null)
                            {
                                <li class="list-group-item d-flex justify-content-between bg-light">

                                    <div class="text-success">
                                        <h6 class="my-0">Promo code</h6>
                                        <small>@ViewBag.Coupon.CouponName</small>
                                    </div>
                                    <span class="text-success"> - $ @ViewBag.Coupon.Discount</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    <span>Total (USD)</span>
                                    <strong>@string.Format("{0:C}", (total - ViewBag.Coupon.Discount))</strong>
                                    <input type="hidden" asp-for="Price" value="@(total - ViewBag.Coupon.Discount)" />
                                </li>
                            }
                            else
                            {
                                <li class="list-group-item d-flex justify-content-between bg-light">

                                    <div class="text-success">
                                        <h6 class="my-0">Promo code</h6>
                                        <small></small>
                                    </div>
                                    <span class="text-success"> </span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    <span>Total (USD)</span>
                                    <strong>@string.Format("{0:C}", total)</strong>
                                    <input type="hidden" asp-for="Price" value="@total" />

                                </li>
                            }

                        </ul>
                    </div>
                </div>
            </form>
        </div>
    </section>
</main>