LaundryOnline/Models/Config.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LaundryOnline.Models
{
    public class Config
    {
        [Key]
        [DisplayName("Config Id")]
        public string ConfigId { get; set; }

        [DisplayName("Description")]
        [Column(TypeName = "ntext")]
        [Required]
        public string Description { get; set; }

        [DisplayName("Email")]
        [Required]
        [EmailAddress]
        public string EmailAddress { get; set; }

        [DisplayName("Phone Number")]
        [Required]
        [Phone]
        public string ContactNumber { get; set; }

        [DisplayName("Address")]
        [Required]
        [StringLength(150)]
        public string Address { get; set; }

        [DisplayName("Status")]
        [DefaultValue(1)]
        public byte Status { get; set; }

        [DisplayName("Image")]
        public string Image { get; set; }
    }
}

LaundryOnline/Areas/Admin/Controllers/ConfigsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaundryOnline.Models;
using X.PagedList;
using System.IO;
using NToastNotify;
using Microsoft.AspNetCore.Authorization;

namespace LaundryOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ConfigsController : Controller
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;

        public ConfigsController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }

        // GET: Admin/Configs
        public async Task<IActionResult> Index(int? page)
        {
            page = page ?? 1;
            int pageSize = 6;
            var configs = _context.Config.AsQueryable();
            return View(await configs.ToPagedListAsync(page, pageSize));
        }

        // GET: Admin/Configs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var config = await _context.Config
                .FirstOrDefaultAsync(m => m.ConfigId == id);
            if (config == null)
            {
                return NotFound();
            }

            return View(config);
        }

        // GET: Admin/Configs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Configs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConfigId,Description,EmailAddress,ContactNumber,Address,Image")] Config config)
        {
            config.Status = 1;
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0 && files[0].Length > 0)
                {
                    var file = files[0];
                    var FileName = file.FileName;

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\config", FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                        config.Image = FileName;
                        _context.Add(config);
                        await _context.SaveChangesAsync();
                    }

                }
                _toastNotification.AddSuccessToastMessage("Create new config successfully");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Create new config failed");
                return View(config);
            }

        }

        // GET: Admin/Configs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var config = await _context.Config.FindAsync(id);
            if (config == null)
            {
                return NotFound();
            }
            return View(config);
        }

        // POST: Admin/Configs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ConfigId,Description,EmailAddress,ContactNumber,Address,Status,Image")] Config config,string img)
        {
            if (id != config.ConfigId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count() > 0 && files[0].Length > 0)
                    {
                        var file = files[0];
                        var FileName = file.FileName;

                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\config", FileName);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(stream);
                            config.Image = FileName;
                        }
                    }
                    else
                    {
                        config.Image = img;
                    }
                    _context.Entry(config).State = EntityState.Modified;
                    await _context.SaveChangesAsync();

                    _toastNotification.AddSuccessToastMessage("Update successfully");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConfigExists(config.EmailAddress))
                    {
                        return NotFound();
                    }
                    else
                    {
                        _toastNotification.AddErrorToastMessage("Update failed");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(config);
        }

        // GET: Admin/Configs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            var config = await _context.Config.FindAsync(id);
            try
            {
                _context.Config.Remove(config);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Delete config successfully");
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Delete config failed");
            }

            return RedirectToAction(nameof(Index));
        }

       
        private bool ConfigExists(string email)
        {
            return _context.Config.Any(e => e.EmailAddress == email);
        }
    }
}

LaundryOnline/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LaundryOnline.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using X.PagedList;

namespace LaundryOnline.Controllers
{
    public class BlogsController : Controller
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;

        public BlogsController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }

        // GET: Admin/Blogs
        public async Task<IActionResult> Index(int? page, string name)
        {
            page = page ?? 1;
            int pageSize = 3;
            var blogs = _context.Blogs.Include(b=>b.User).Where(b => b.Status == 1).AsQueryable();
            ViewBag.blogNews = _context.Blogs.Include(b => b.User).Where(b=>b.Status==1).Take(3);
            
            if (!string.IsNullOrEmpty(name))
            {
                blogs = blogs.Where(j => j.Title.Contains(name));
            }
            return View(await blogs.ToPagedListAsync(page, pageSize));
        }

        // GET: Admin/Blogs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            ViewBag.blogNews = _context.Blogs.Include(b => b.User).Take(3);
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }
    }
}

LaundryOnline/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LaundryOnline.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NToastNotify;

namespace LaundryOnline.Controllers
{
    public class CartController : Controller, IActionFilter
    {
        private readonly LaundryOnlineContext _context;
        private readonly IToastNotification _toastNotification;
        private List<Cart> listCarts = new List<Cart>();

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var cartInSession = HttpContext.Session.GetString("ShoppingCart");
            if (cartInSession != null)
            {
                listCarts = JsonConvert.DeserializeObject<List<Cart>>(cartInSession);
            }
            
            base.OnActionExecuting(context);
        }

        public CartController(LaundryOnlineContext context, IToastNotification toastrNotification)
        {
            _context = context;
            _toastNotification = toastrNotification;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("CustomerLogin") != null)
            {
                List<Coupon> AllCoupons = _context.Coupons.ToList();
                List<Coupon> Coupon = new List<Coupon>();
                var listUsedCoupon = _context.UsedCoupons.Where(u => u.UserId == HttpContext.Session.GetString("CustomerId")).ToList();
                foreach (var item in AllCoupons)
                {
                    bool check = false;
                    foreach (var i in listUsedCoupon)
                    {
                        if (item.CouponId.Equals(i.CouponId))
                        {
                            check = true;
                        }
                    }
                    if (check)
                    {
                        continue;
                    }
                    Coupon.Add(item);
                }
                ViewBag.coupons = Coupon;
            }
            if (HttpContext.Session.GetString("Coupon") != null)
            {
                ViewBag.Coupon = _context.Coupons.Find(HttpContext.Session.GetString("Coupon"));
            }
            return View(listCarts);
        }
        public IActionResult AddCart(string id)
        {
            if (listCarts.Any(c => c.UnitId == id))
            {
                listCarts.Where(c => c.UnitId == id).First().Quantity += 1;
            }
            else
            {
                var unit = _context.Units.Find(id);
                var cart = new Cart()
                {
                    UnitId = unit.UnitId,
                    UnitName = unit.UnitName,
                    Image = unit.Image,
                    UnitPrice = unit.UnitPrice,
                    Quantity = 1
                };
                listCarts.Add(cart);
            }
            HttpContext.Session.SetString("ShoppingCart", JsonConvert.SerializeObject(listCarts));
            _toastNotification.AddSuccessToastMessage("Add cart successfully");
            return RedirectToAction(nameof(Index));
        }
        public IActionResult RemoveItemCart(string id)
        {
            if (listCarts.Any(c => c.UnitId == id))
            {
                var remove = listCarts.Where(c => c.UnitId == id).First();
                listCarts.Remove(remove);
                HttpContext.Session.SetString("ShoppingCart", JsonConvert.SerializeObject(listCarts));
                _toastNotification.AddSuccessToastMessage("Remove item successfully");
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult IncreaseQtyCart(string id)
        {
            if (HttpContext.Session.GetString("CustomerLogin") != null)
            {
                ViewBag.coupons = _context.Coupons;
            }
            if (listCarts.Any(c => c.UnitId == id))
            {
                listCarts.Where(c => c.UnitId == id).First().Quantity += 1;
                HttpContext.Session.SetString("ShoppingCart", JsonConvert.SerializeObject(listCarts));
                _toastNotification.AddSuccessToastMessage("Update cart successfully");
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DecreaseQtyCart(string id)
        {
            if (listCarts.Any(c => c.UnitId == id))
            {
                var cart = listCarts.Where(c => c.UnitId == id).First();
                if (cart.Quantity <= 1)
                {
                    cart.Quantity = 1;
                }
                else
                {
                    cart.Quantity -= 1;
                }
                HttpContext.Session.SetString("ShoppingCart", JsonConvert.SerializeObject(listCarts));
                _toastNotification.AddSuccessToastMessage("Update cart successfully");
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Clear()
        {
            HttpContext.Session.Remove("ShoppingCart");
            HttpContext.Session.Remove("Coupon");
            _toastNotification.AddSuccessToastMessage("Clear cart successfully");
            return RedirectToAction(nameof(Index));
        }
        public IActionResult AddCoupon(string coupon)
        {
            if (String.IsNullOrEmpty(coupon))
            {
                HttpContext.Session.Remove("Coupon");
            }
            else
            {
                var cou = _context.Coupons.Find(coupon);
                HttpContext.Session.SetString("Coupon", cou.CouponId);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

LaundryOnline/Views/Shared/Components/Config/Default.cshtml
@model LaundryOnline.Models.Config

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<div class="tp-header-top theme-dark-bg pt-20 pb-50 d-none d-xl-block">
    <div class="tp-custom-container">
        <div class="row align-items-center">
            <div class="col-xxl-4 col-xl-5">
                <div class="tp-header-top-info">
                    <div class="tp-header-top-info-single pr-40 mr-40 border-right-1">
                        <div class="tp-header-top-info-single-icon mr-10">
                            <i class="flaticon-pin"></i>
                        </div>
                        <div class="tp-header-top-info-single-text">
                            <span class="tp-header-top-info-single-label">Free Contact</span>
                            <span class="tp-header-top-info-single-content font-medium">
                                @Model.Address
                            </span>
                        </div>
                    </div>
                    <div class="tp-header-top-info-single">
                        <div class="tp-header-top-info-single-icon mr-15">
                            <i class="flaticon-email"></i>
                        </div>
                        <div class="tp-header-top-info-single-text">
                            <span class="tp-header-top-info-single-label">Email us</span>
                            <a class="tp-header-top-info-single-content font-medium"><span class="__cf_email__">@Model.EmailAddress</span></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xxl-4 col-xl-2">
                <div class="header-logo text-center">
                    <a asp-controller="Home" asp-action="Index"><img src="~/images/config/logo.png" class="img-fluid" alt=""></a>
                </div>
            </div>
            <div class="col-xxl-4 col-xl-5">
                <div class="tp-header-top-info justify-content-end">
                    <div class="tp-header-top-info-single mr-85">
                        <div class="tp-header-top-info-single-icon tp-header-top-info-single-icon-call mr-10">
                            <i class="flaticon-phone-call"></i>
                        </div>
                        <div class="tp-header-top-info-single-text">
                            <span class="tp-header-top-info-single-label">Free Call</span>
                            <a href="tel:33388820055" class="tp-header-top-info-single-content font-medium">@Model.ContactNumber</a>
                        </div>
                    </div>
                    <div class="tp-header-top-info-single">
                        <div class="tp-header-top-info-single-btn">
                            @if (HttpContextAccessor.HttpContext.Session.GetString("CustomerLogin") != null)
                            {
                                <a asp-controller="Accounts" asp-action="Logout" class="yellow-btn"><i class="flaticon-enter"></i> Logout</a>
                            }
                            else
                            {
                                <a asp-controller="Accounts" asp-action="Login" class="yellow-btn"><i class="flaticon-enter"></i> Login</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="tp-header-menu-area tp-transparent-header-menu header-sticky">
    <div class="container">
        <div class="row justify-content-xl-center align-items-center">
            <div class="col-xl-2 col-8 tp-sticky-column">
                <div class="tp-sticky-logo">
                    <a asp-controller="Home" asp-action="Index"><img src="~/images/config/@Model.Image" class="img-fluid" alt="logo not found"></a>
                </div>
            </div>
            <div class="col-xl-8 col-4">
                <div class="tp-main-menu-bg">
                    <div class="tp-main-menu">
                        <nav id="tp-mobile-menu">
                            <ul class="text-center">
                                <li class="">
                                    <a asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="menu-item-has-children">
                                    <a asp-controller="Services" asp-action="Index">Services</a>
                                    @await Component.InvokeAsync("Services")
                                </li>
                                <li class="">
                                    <a asp-controller="Blogs" asp-action="Index">Blogs</a>
                                </li>
                                <li class="">
                                    <a asp-controller="Cart" asp-action="Index">Cart</a>
                                </li>
                                @if (HttpContextAccessor.HttpContext.Session.GetString("CustomerLogin") != null)
                                {
                                    <li class="menu-item-has-children">
                                        <a href="#">@HttpContextAccessor.HttpContext.Session.GetString("CustomerLogin")</a>
                                        <ul class="sub-menu">
                                            <li><a asp-controller="Accounts" asp-action="Details">My Account</a></li>
                                            <li><a asp-controller="Accounts" asp-action="ChangePassword">Change Password</a></li>
                                            <li><a asp-controller="Orders" asp-action="Index">My Order</a></li>
                                            <li><a asp-controller="Accounts" asp-action="Logout">Logout</a></li>
                                        </ul>
                                    </li>
                                }
                                else
                                {
                                    <li class="">
                                        <a asp-controller="Orders" asp-action="CheckBill">Check Bill</a>
                                    </li>
                                    <li class="menu-item-has-children">
                                        <a asp-controller="Accounts" asp-action="Login">Login</a>
                                        <ul class="sub-menu">
                                            <li><a asp-controller="Accounts" asp-action="Login"> Login</a></li>
                                            <li><a asp-controller="Accounts" asp-action="Register">Register</a></li>
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                    <!-- mobile menu activation -->
                    <div class="side-menu-icon d-xl-none text-end">
                        <button class="side-toggle"><i class="far fa-bars"></i></button>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 tp-sticky-column-btn">
                <div class="tp-sticky-btn text-end">
                    @if (HttpContextAccessor.HttpContext.Session.GetString("CustomerLogin") != null)
                    {
                        <a asp-controller="Accounts" asp-action="Logout" class="theme-btn justify-content-end">
                            <i class="flaticon-enter"></i> Logout
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Accounts" asp-action="Login" class="theme-btn justify-content-end">
                            <i class="flaticon-enter"></i> Login
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fix">
    <div class="side-info">
        <button class="side-info-close"><i class="fal fa-times"></i></button>
        <div class="side-info-content">
            <div class="tp-mobile-menu"></div>
            <div class="contact-infos mb-30">
                <div class="contact-list mb-30">
                    <h4>Contact Info</h4>
                    <ul>
                        <li><i class="flaticon-pin"></i>@Model.Address</li>
                        <li><i class="flaticon-email"></i><a href=""><span class="__cf_email__">@Model.EmailAddress</span></a></li>
                        <li><i class="flaticon-phone-call"></i><a href="tel:33388820055">@Model.ContactNumber</a></li>
                    </ul>
                    <div class="sidebar__menu--social">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-google"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>